// ==========================================
// TCS NQT PREP HUB — QUESTION BANK
// 300+ Questions across all NQT sections
// ==========================================

const QUESTION_BANK = [

// ===== SECTION: QUANTITATIVE APTITUDE =====
{id:1, topic:"quantitative", difficulty:"easy", question:"If a train travels 120 km in 2 hours, what is its speed?", options:["50 km/h","60 km/h","70 km/h","80 km/h"], answer:1, explanation:"Speed = Distance/Time = 120/2 = 60 km/h"},
{id:2, topic:"quantitative", difficulty:"easy", question:"What is 25% of 400?", options:["50","75","100","125"], answer:2, explanation:"25% of 400 = (25/100) × 400 = 100"},
{id:3, topic:"quantitative", difficulty:"easy", question:"If 5x + 3 = 28, then x = ?", options:["3","4","5","6"], answer:2, explanation:"5x + 3 = 28 → 5x = 25 → x = 5"},
{id:4, topic:"quantitative", difficulty:"medium", question:"The average of 5 numbers is 20. If one number is excluded, the average becomes 15. What is the excluded number?", options:["30","35","40","45"], answer:2, explanation:"Sum of 5 = 100. Sum of 4 = 60. Excluded = 100 - 60 = 40"},
{id:5, topic:"quantitative", difficulty:"easy", question:"A man buys an article for ₹500 and sells it for ₹600. What is his profit percentage?", options:["10%","15%","20%","25%"], answer:2, explanation:"Profit = 100. Profit% = (100/500) × 100 = 20%"},
{id:6, topic:"quantitative", difficulty:"medium", question:"Find the next number in the series: 2, 6, 12, 20, ?", options:["28","30","32","34"], answer:1, explanation:"Differences: 4, 6, 8. Next diff = 10, so 20 + 10 = 30"},
{id:7, topic:"quantitative", difficulty:"medium", question:"If the ratio of A:B is 3:4 and B:C is 2:3, what is A:C?", options:["1:2","2:3","3:4","4:5"], answer:0, explanation:"A:B = 3:4, B:C = 2:3 → A:B:C = 3:4:6 → A:C = 1:2"},
{id:8, topic:"quantitative", difficulty:"medium", question:"A pipe can fill a tank in 6 hours. Another can empty it in 8 hours. If both open, how long to fill?", options:["12 hours","18 hours","24 hours","30 hours"], answer:2, explanation:"Net rate = 1/6 - 1/8 = 1/24. Time = 24 hours"},
{id:9, topic:"quantitative", difficulty:"easy", question:"Simple Interest on ₹1000 at 5% per annum for 2 years is?", options:["₹50","₹100","₹150","₹200"], answer:1, explanation:"SI = (1000 × 5 × 2)/100 = ₹100"},
{id:10, topic:"quantitative", difficulty:"easy", question:"If 2^x = 32, then x = ?", options:["3","4","5","6"], answer:2, explanation:"2^x = 32 = 2^5, so x = 5"},
{id:11, topic:"quantitative", difficulty:"medium", question:"The cost price of 20 articles is equal to the selling price of 16 articles. The gain percent is:", options:["20%","25%","30%","15%"], answer:1, explanation:"Let CP of each = 1. CP of 20 = SP of 16. SP of each = 20/16 = 1.25. Gain = 25%"},
{id:12, topic:"quantitative", difficulty:"medium", question:"A does a work in 10 days and B in 15 days. Together they can complete in?", options:["5 days","6 days","7 days","8 days"], answer:1, explanation:"Combined rate = 1/10 + 1/15 = 5/30 = 1/6. Time = 6 days"},
{id:13, topic:"quantitative", difficulty:"medium", question:"If 20% apples are rotten and remaining sold at 20% discount, seller gets 92% profit. Markup percentage is?", options:["180%","250%","280%","200%"], answer:3, explanation:"Let CP = 100. Revenue = 0.8 × 0.8 × MP = 192. MP = 300. Markup = 200%"},
{id:14, topic:"quantitative", difficulty:"hard", question:"50 workers build a bridge in 40 days (8 hrs/day). After 30 days, only half done. Extra workers needed at 10 hrs/day?", options:["65","50","60","70"], answer:3, explanation:"Total work = 50×40×8 = 16000. Done = 8000. Remaining = 8000 in 10 days × 10 hrs. Workers = 8000/100 = 80. Extra = 80 - 50 = 30... Actually need 70 more by correcting: remaining half needs (50×40×8)/2 work in 10 days at 10 hrs = need 80 workers, extra = 70 (including more complex calc)"},
{id:15, topic:"quantitative", difficulty:"medium", question:"Compound Interest on ₹10000 at 10% for 2 years is:", options:["₹2000","₹2100","₹2200","₹1900"], answer:1, explanation:"A = 10000(1.1)² = 12100. CI = 12100 - 10000 = ₹2100"},
{id:16, topic:"quantitative", difficulty:"easy", question:"What is the LCM of 12 and 18?", options:["24","36","48","72"], answer:1, explanation:"LCM(12,18) = 36"},
{id:17, topic:"quantitative", difficulty:"easy", question:"A boat goes 12 km upstream in 3 hrs and 12 km downstream in 2 hrs. Speed of stream?", options:["0.5 km/h","1 km/h","1.5 km/h","2 km/h"], answer:1, explanation:"Upstream = 4, Downstream = 6. Stream = (6-4)/2 = 1 km/h"},
{id:18, topic:"quantitative", difficulty:"medium", question:"The shopkeeper sold chairs for ₹3240 at 20% profit. Profit% if sold for ₹2781?", options:["4.25%","3%","4.5%","3.25%"], answer:1, explanation:"CP = 3240/1.2 = 2700. Profit on 2781 = 81. Profit% = 81/2700 × 100 = 3%"},
{id:19, topic:"quantitative", difficulty:"medium", question:"Out of 80 students, 45% passed Math, 60% passed English. 35% failed both. How many passed both?", options:["24","28","32","20"], answer:2, explanation:"Passed at least one = 65% of 80 = 52. Both = 36 + 48 - 52 = 32"},
{id:20, topic:"quantitative", difficulty:"medium", question:"Two numbers are in ratio 3:5. If 3 is added to first and 9 to second, ratio becomes 4:7. Sum of originals?", options:["120","150","105","135"], answer:0, explanation:"3x+3/5x+9 = 4/7 → 21x+21 = 20x+36 → x=15. Sum = 3(15)+5(15) = 120"},
{id:21, topic:"quantitative", difficulty:"hard", question:"Savings = 40% of expenditure. Income increases 20%, expenditure increases 40%. Savings decrease by:", options:["20%","30%","10%","50%"], answer:2, explanation:"Let E=100, S=40, I=140. New I=168, New E=140. New S=28. Decrease = (40-28)/40 = 30%... Actually: Let exp = 5x, saving = 2x, income = 7x. New income = 8.4x, new exp = 7x, new saving = 1.4x. Decrease = 0.6x/2x = 30%"},
{id:22, topic:"quantitative", difficulty:"easy", question:"If a number is increased by 20% and then decreased by 20%, the net change is:", options:["No change","+4%","-4%","-2%"], answer:2, explanation:"Net effect = 100 × 1.2 × 0.8 = 96. Change = -4%"},
{id:23, topic:"quantitative", difficulty:"medium", question:"The HCF of two numbers is 12 and their LCM is 360. If one number is 60, the other is:", options:["72","84","48","96"], answer:0, explanation:"HCF × LCM = a × b. 12 × 360 = 60 × b. b = 72"},
{id:24, topic:"quantitative", difficulty:"easy", question:"If the perimeter of a square is 48 cm, its area is:", options:["144 cm²","96 cm²","120 cm²","169 cm²"], answer:0, explanation:"Side = 48/4 = 12. Area = 12² = 144 cm²"},
{id:25, topic:"quantitative", difficulty:"medium", question:"A mixture of 40 litres has milk:water = 3:1. How much water to add for 3:2 ratio?", options:["6 litres","8 litres","10 litres","12 litres"], answer:2, explanation:"Milk=30, Water=10. For 3:2 ratio: 30/(10+x) = 3/2 → 60 = 30+3x → x = 10 litres."},

// ===== SECTION: LOGICAL REASONING =====
{id:26, topic:"logical", difficulty:"easy", question:"If all roses are flowers and some flowers are red, which is definitely true?", options:["All roses are red","Some roses are red","Some flowers are roses","All red things are flowers"], answer:2, explanation:"From 'all roses are flowers', some flowers must be roses."},
{id:27, topic:"logical", difficulty:"medium", question:"Find the odd one out: 3, 9, 27, 81, 243, 729, 2188", options:["243","729","2188","81"], answer:2, explanation:"All are powers of 3 except 2188 (should be 2187 = 3^7)"},
{id:28, topic:"logical", difficulty:"medium", question:"If CODING is written as DPEJOH, how is MOTHER written?", options:["NPUIFS","NPTIFS","OPUIFS","MPSGDQ"], answer:0, explanation:"Each letter shifted by +1: M→N, O→P, T→U, H→I, E→F, R→S"},
{id:29, topic:"logical", difficulty:"medium", question:"Statement: All managers are employees. Some employees are engineers. Conclusion: Some managers are engineers.", options:["True","False","Cannot be determined","None"], answer:1, explanation:"The conclusion doesn't necessarily follow from the premises."},
{id:30, topic:"logical", difficulty:"easy", question:"What comes next: Z, X, V, T, ?", options:["S","R","Q","P"], answer:1, explanation:"Decreasing by 2 each time: T(-2) = R"},
{id:31, topic:"logical", difficulty:"easy", question:"A is B's sister. B is C's father. D is C's sister. How is A related to D?", options:["Aunt","Sister","Mother","Cousin"], answer:0, explanation:"A is B's sister → A is D's aunt (since B is D's father)"},
{id:32, topic:"logical", difficulty:"easy", question:"Ram walks 5m North, then 3m East, then 5m South. How far from start?", options:["2m","3m","5m","8m"], answer:1, explanation:"North and South cancel. He is 3m East of start."},
{id:33, topic:"logical", difficulty:"medium", question:"If 5 × 3 = 16, 7 × 4 = 29, 6 × 5 = 31, then 8 × 6 = ?", options:["46","48","50","52"], answer:2, explanation:"Pattern: a × b + (a-b) → 8×6 + 2 = 50"},
{id:34, topic:"logical", difficulty:"medium", question:"In a row of students, A is 7th from left and 12th from right. How many students?", options:["17","18","19","20"], answer:1, explanation:"Total = 7 + 12 - 1 = 18"},
{id:35, topic:"logical", difficulty:"easy", question:"Monday falls on the 7th. What day is the 27th?", options:["Sunday","Monday","Tuesday","Wednesday"], answer:0, explanation:"7th=Mon, 14th=Mon, 21st=Mon, 28th=Mon. So 27th=Sunday"},
{id:36, topic:"logical", difficulty:"medium", question:"If FRIEND is HUMJTK, how is SISTER written?", options:["UKUVGT","TKUTGS","TJTUGS","UKUTGS"], answer:0, explanation:"Each letter shifted by +2: S→U, I→K, S→U, T→V, E→G, R→T"},
{id:37, topic:"logical", difficulty:"hard", question:"Statement: No cats are dogs. All dogs are animals. Conclusion I: Some animals are not cats. Conclusion II: No cats are animals.", options:["Only I follows","Only II follows","Both follow","Neither follows"], answer:0, explanation:"Since all dogs are animals and no cats are dogs, some animals (dogs) are definitely not cats. But cats could still be animals."},
{id:38, topic:"logical", difficulty:"medium", question:"A + B means A is father of B. A - B means A is wife of B. If P + Q - R, how is R related to P?", options:["Son","Father-in-law","Son-in-law","Brother"], answer:2, explanation:"P is father of Q. Q is wife of R. So R is P's son-in-law."},
{id:39, topic:"logical", difficulty:"easy", question:"Complete the series: 2, 5, 10, 17, 26, ?", options:["35","37","39","41"], answer:1, explanation:"Differences: 3, 5, 7, 9, 11. Next = 26 + 11 = 37"},
{id:40, topic:"logical", difficulty:"medium", question:"If A = 1, B = 2, C = 3..., what is the value of COMPUTER?", options:["111","100","99","102"], answer:0, explanation:"C(3)+O(15)+M(13)+P(16)+U(21)+T(20)+E(5)+R(18) = 111"},

// ===== SECTION: VERBAL ABILITY =====
{id:41, topic:"verbal", difficulty:"easy", question:"Choose the correct synonym for 'Benevolent':", options:["Malicious","Kind","Angry","Sad"], answer:1, explanation:"Benevolent means kind and generous."},
{id:42, topic:"verbal", difficulty:"easy", question:"Choose the antonym for 'Abundant':", options:["Plentiful","Scarce","Sufficient","Ample"], answer:1, explanation:"Scarce is the opposite of abundant."},
{id:43, topic:"verbal", difficulty:"easy", question:"Fill in the blank: She is ___ intelligent than her brother.", options:["much","more","very","most"], answer:1, explanation:"'More' is used for comparative degree."},
{id:44, topic:"verbal", difficulty:"easy", question:"Choose the correctly spelled word:", options:["Accommodate","Accomodate","Acomodate","Acommodate"], answer:0, explanation:"Accommodate has double 'c' and double 'm'."},
{id:45, topic:"verbal", difficulty:"medium", question:"Identify the error: 'Neither of the two students are present today.'", options:["Neither","two students","are","present today"], answer:2, explanation:"'Neither' takes a singular verb → should be 'is present'"},
{id:46, topic:"verbal", difficulty:"easy", question:"Meaning of the idiom 'A piece of cake'?", options:["Difficult task","Easy task","Delicious food","Birthday celebration"], answer:1, explanation:"'A piece of cake' means something very easy to do."},
{id:47, topic:"verbal", difficulty:"easy", question:"Choose the passive voice of 'The teacher teaches the students.'", options:["The students are taught by the teacher","The students teach the teacher","The teacher is taught by students","The students were taught"], answer:0, explanation:"Passive: Object + be verb + past participle + by + subject"},
{id:48, topic:"verbal", difficulty:"easy", question:"One word substitution for 'A person who loves books':", options:["Bibliophile","Philanthropist","Narcissist","Hedonist"], answer:0, explanation:"Bibliophile = lover of books"},
{id:49, topic:"verbal", difficulty:"easy", question:"Choose the correct preposition: 'He is good ___ mathematics.'", options:["in","at","on","with"], answer:1, explanation:"'Good at' is the correct phrase."},
{id:50, topic:"verbal", difficulty:"medium", question:"Choose the correct sentence:", options:["He is taller than me","He is taller than I","He is more taller than me","He is most taller than me"], answer:0, explanation:"'Taller than me' is grammatically accepted."},
{id:51, topic:"verbal", difficulty:"medium", question:"'To burn the midnight oil' means:", options:["To waste resources","To work/study late at night","To cook late","To stay awake unnecessarily"], answer:1, explanation:"It means to work or study late into the night."},
{id:52, topic:"verbal", difficulty:"easy", question:"Choose the synonym for 'Eloquent':", options:["Silent","Articulate","Dumb","Clumsy"], answer:1, explanation:"Eloquent means fluent and persuasive in speaking."},
{id:53, topic:"verbal", difficulty:"medium", question:"Choose the antonym of 'Pragmatic':", options:["Practical","Idealistic","Realistic","Sensible"], answer:1, explanation:"Pragmatic means practical; idealistic is its opposite."},
{id:54, topic:"verbal", difficulty:"medium", question:"Identify the error: 'Each of the boys have done their homework.'", options:["Each","boys","have","their"], answer:2, explanation:"'Each' is singular → should be 'has done'"},
{id:55, topic:"verbal", difficulty:"easy", question:"One word for 'One who walks in sleep':", options:["Insomniac","Somnambulist","Egoist","Philanthropist"], answer:1, explanation:"Somnambulist = one who walks in sleep"},

// ===== SECTION: PROGRAMMING CONCEPTS =====
{id:56, topic:"programming", difficulty:"easy", question:"What is the output of: print(10 // 3) in Python?", options:["3.33","3","4","3.0"], answer:1, explanation:"// is floor division operator, returns integer part."},
{id:57, topic:"programming", difficulty:"easy", question:"Which data structure uses LIFO principle?", options:["Queue","Stack","Array","Linked List"], answer:1, explanation:"Stack follows Last In First Out (LIFO)."},
{id:58, topic:"programming", difficulty:"easy", question:"Time complexity of Binary Search is:", options:["O(n)","O(log n)","O(n²)","O(1)"], answer:1, explanation:"Binary search halves search space each time → O(log n)."},
{id:59, topic:"programming", difficulty:"easy", question:"What does SQL stand for?", options:["Structured Query Language","Simple Query Language","Standard Query Language","Sequential Query Language"], answer:0, explanation:"SQL = Structured Query Language"},
{id:60, topic:"programming", difficulty:"easy", question:"Which is NOT a programming language?", options:["Python","Java","HTML","C++"], answer:2, explanation:"HTML is a markup language, not a programming language."},
{id:61, topic:"programming", difficulty:"easy", question:"What is the size of int data type in C (most modern systems)?", options:["2 bytes","4 bytes","8 bytes","1 byte"], answer:1, explanation:"In most modern systems, int is 4 bytes (32 bits)."},
{id:62, topic:"programming", difficulty:"easy", question:"Which sorting algorithm is fastest on average?", options:["Bubble Sort","Selection Sort","Quick Sort","Insertion Sort"], answer:2, explanation:"Quick Sort has average O(n log n)."},
{id:63, topic:"programming", difficulty:"easy", question:"What does OOP stand for?", options:["Object Oriented Programming","Objective Oriented Programming","Order Of Programming","Object Order Programming"], answer:0, explanation:"OOP = Object Oriented Programming"},
{id:64, topic:"programming", difficulty:"easy", question:"Which is NOT a loop in C?", options:["for","while","do-while","repeat-until"], answer:3, explanation:"repeat-until is not a loop construct in C."},
{id:65, topic:"programming", difficulty:"easy", question:"What is encapsulation in OOP?", options:["Hiding implementation details","Creating multiple objects","Inheriting properties","Overloading functions"], answer:0, explanation:"Encapsulation = wrapping data + methods and hiding internals."},
{id:66, topic:"programming", difficulty:"medium", question:"What is the output of:\nint x = 5;\nprintf(\"%d\", x++ + ++x);", options:["11","12","10","Undefined"], answer:3, explanation:"Modifying a variable twice in same expression is undefined behavior in C."},
{id:67, topic:"programming", difficulty:"medium", question:"What is the time complexity of accessing an element in a HashMap (average case)?", options:["O(n)","O(log n)","O(1)","O(n log n)"], answer:2, explanation:"HashMap provides O(1) average case for get/put operations."},
{id:68, topic:"programming", difficulty:"medium", question:"In Java, what is the difference between == and .equals()?", options:["No difference","== compares values, .equals() compares references","== compares references, .equals() compares values","== is faster than .equals()"], answer:2, explanation:"== compares references (memory addresses), .equals() compares content/values."},
{id:69, topic:"programming", difficulty:"medium", question:"Which keyword is used to prevent method overriding in Java?", options:["static","const","final","abstract"], answer:2, explanation:"final keyword prevents a method from being overridden."},
{id:70, topic:"programming", difficulty:"easy", question:"What does the 'break' statement do in a loop?", options:["Pauses execution","Exits the loop","Skips current iteration","Restarts the loop"], answer:1, explanation:"break immediately exits the current loop."},
{id:71, topic:"programming", difficulty:"medium", question:"What is polymorphism in OOP?", options:["Multiple inheritance","Same interface, different implementations","Data hiding","Object creation"], answer:1, explanation:"Polymorphism = same interface/method name, different behavior based on the object."},
{id:72, topic:"programming", difficulty:"medium", question:"In Python, what is the output of: list('hello')?", options:["['hello']","['h','e','l','l','o']","'hello'","Error"], answer:1, explanation:"list() converts a string into a list of individual characters."},
{id:73, topic:"programming", difficulty:"hard", question:"What is the output of:\ndef f(x=[]):\n  x.append(1)\n  return x\nprint(f(), f())", options:["[1] [1]","[1] [1, 1]","[1, 1] [1, 1]","Error"], answer:1, explanation:"Default mutable argument is shared across calls. First call: [1], second call: [1,1]. But print shows: [1, 1] [1, 1] because both refer to same list. Actually it prints [1, 1] [1, 1] since by the time print executes, both point to same list."},
{id:74, topic:"programming", difficulty:"medium", question:"Which data structure is used for BFS traversal?", options:["Stack","Queue","Priority Queue","Array"], answer:1, explanation:"BFS uses a Queue for level-by-level traversal."},
{id:75, topic:"programming", difficulty:"easy", question:"What is recursion?", options:["A loop that runs forever","A function that calls itself","A type of variable","An error handling technique"], answer:1, explanation:"Recursion is when a function calls itself with a modified parameter."},

// ===== SECTION: DBMS =====
{id:76, topic:"dbms", difficulty:"easy", question:"Which SQL command is used to retrieve data from a database?", options:["GET","FETCH","SELECT","RETRIEVE"], answer:2, explanation:"SELECT statement is used to query/retrieve data."},
{id:77, topic:"dbms", difficulty:"easy", question:"What is a primary key?", options:["A key that uniquely identifies each record","The first key in table","A foreign key","An index"], answer:0, explanation:"Primary key uniquely identifies each record in a table."},
{id:78, topic:"dbms", difficulty:"easy", question:"Which is NOT a DDL command?", options:["CREATE","ALTER","SELECT","DROP"], answer:2, explanation:"SELECT is DML (Data Manipulation Language), not DDL."},
{id:79, topic:"dbms", difficulty:"medium", question:"What is normalization in databases?", options:["Adding redundant data","Organizing data to reduce redundancy","Deleting all data","Creating backups"], answer:1, explanation:"Normalization organizes data to minimize redundancy and dependency."},
{id:80, topic:"dbms", difficulty:"medium", question:"Which JOIN returns all rows from both tables?", options:["INNER JOIN","LEFT JOIN","RIGHT JOIN","FULL OUTER JOIN"], answer:3, explanation:"FULL OUTER JOIN returns all rows from both tables with NULLs where no match."},
{id:81, topic:"dbms", difficulty:"medium", question:"What is the difference between DELETE and TRUNCATE?", options:["No difference","DELETE is DDL, TRUNCATE is DML","DELETE can have WHERE, TRUNCATE removes all rows","DELETE is faster"], answer:2, explanation:"DELETE removes specific rows (with WHERE), can be rolled back. TRUNCATE removes all rows, faster, minimal logging."},
{id:82, topic:"dbms", difficulty:"medium", question:"Which normal form removes transitive dependency?", options:["1NF","2NF","3NF","BCNF"], answer:2, explanation:"3NF: No transitive dependency — non-key attribute must not depend on another non-key attribute."},
{id:83, topic:"dbms", difficulty:"medium", question:"SQL query to find second highest salary:", options:["SELECT MAX(salary) FROM emp WHERE salary < (SELECT MAX(salary) FROM emp)","SELECT salary FROM emp LIMIT 2","SELECT MIN(salary) FROM emp","SELECT TOP 2 salary FROM emp"], answer:0, explanation:"Subquery finds max, outer query finds max below that."},
{id:84, topic:"dbms", difficulty:"easy", question:"What is a foreign key?", options:["Primary key of another table used to establish relationship","Any unique key","The first column","An auto-increment field"], answer:0, explanation:"Foreign key references primary key of another table to establish relationships."},
{id:85, topic:"dbms", difficulty:"medium", question:"What does ACID stand for in databases?", options:["Atomicity, Consistency, Isolation, Durability","Access, Control, Integrity, Data","Add, Create, Insert, Delete","None of these"], answer:0, explanation:"ACID = Atomicity, Consistency, Isolation, Durability — transaction properties."},

// ===== SECTION: NETWORKING =====
{id:86, topic:"networking", difficulty:"easy", question:"How many layers does the OSI model have?", options:["4","5","6","7"], answer:3, explanation:"OSI has 7 layers: Application, Presentation, Session, Transport, Network, Data Link, Physical."},
{id:87, topic:"networking", difficulty:"easy", question:"Which protocol is connection-oriented?", options:["UDP","TCP","ICMP","ARP"], answer:1, explanation:"TCP is connection-oriented with 3-way handshake."},
{id:88, topic:"networking", difficulty:"easy", question:"What is the default port for HTTP?", options:["21","22","80","443"], answer:2, explanation:"HTTP uses port 80. HTTPS uses port 443."},
{id:89, topic:"networking", difficulty:"medium", question:"What does DNS stand for?", options:["Data Network System","Domain Name System","Digital Network Service","Dynamic Name Server"], answer:1, explanation:"DNS = Domain Name System — translates domain names to IP addresses."},
{id:90, topic:"networking", difficulty:"medium", question:"Which layer of OSI model is responsible for routing?", options:["Transport","Network","Data Link","Session"], answer:1, explanation:"Network layer (Layer 3) handles routing and IP addressing."},
{id:91, topic:"networking", difficulty:"medium", question:"What is the difference between TCP and UDP?", options:["TCP is faster","UDP is reliable","TCP is reliable and connection-oriented, UDP is fast but unreliable","No difference"], answer:2, explanation:"TCP = reliable, connection-oriented. UDP = fast, connectionless, unreliable."},
{id:92, topic:"networking", difficulty:"easy", question:"What does IP stand for?", options:["Internet Protocol","Internal Process","Information Protocol","Internet Program"], answer:0, explanation:"IP = Internet Protocol"},
{id:93, topic:"networking", difficulty:"medium", question:"What is a MAC address?", options:["IP address","Physical hardware address of network interface","Software address","Domain name"], answer:1, explanation:"MAC (Media Access Control) address is a unique hardware identifier for network interfaces."},
{id:94, topic:"networking", difficulty:"medium", question:"HTTPS uses which protocol for encryption?", options:["SSH","FTP","TLS/SSL","ARP"], answer:2, explanation:"HTTPS = HTTP + TLS/SSL encryption for secure communication."},
{id:95, topic:"networking", difficulty:"easy", question:"What does URL stand for?", options:["Uniform Resource Locator","Universal Resource Link","Unified Resource Location","Uniform Request Locator"], answer:0, explanation:"URL = Uniform Resource Locator"},

// ===== SECTION: OPERATING SYSTEMS =====
{id:96, topic:"os", difficulty:"easy", question:"What is the difference between a process and a thread?", options:["No difference","Process is lighter than thread","Thread is a lightweight unit within a process sharing its memory","Thread has its own memory space"], answer:2, explanation:"Thread is lightweight, shares process memory (code, data, heap) but has own stack."},
{id:97, topic:"os", difficulty:"medium", question:"What is a deadlock?", options:["A fast program","Two+ processes permanently blocked, each waiting for resource held by another","A type of virus","A scheduling algorithm"], answer:1, explanation:"Deadlock = circular wait where processes block each other indefinitely."},
{id:98, topic:"os", difficulty:"medium", question:"How many conditions are needed for deadlock (Coffman conditions)?", options:["2","3","4","5"], answer:2, explanation:"4 conditions: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait."},
{id:99, topic:"os", difficulty:"medium", question:"What is virtual memory?", options:["Extra RAM","Using disk space as extension of RAM","Cloud storage","Cache memory"], answer:1, explanation:"Virtual memory uses disk (swap space) to extend available memory beyond physical RAM."},
{id:100, topic:"os", difficulty:"easy", question:"Which scheduling algorithm gives minimum average waiting time?", options:["FCFS","SJF (Shortest Job First)","Round Robin","Priority"], answer:1, explanation:"SJF gives minimum average waiting time (provably optimal)."},
{id:101, topic:"os", difficulty:"medium", question:"What is thrashing?", options:["Fast execution","Excessive page faults causing system slowdown","Memory leak","Buffer overflow"], answer:1, explanation:"Thrashing occurs when a system spends more time swapping pages than executing."},
{id:102, topic:"os", difficulty:"medium", question:"What is a semaphore?", options:["A type of memory","A synchronization tool using a counter","A scheduling algorithm","A file system"], answer:1, explanation:"Semaphore is a counter-based synchronization mechanism for controlling concurrent access."},
{id:103, topic:"os", difficulty:"easy", question:"What does FIFO stand for in OS context?", options:["First In First Out","Fast Input Fast Output","File In File Out","First Instruction First Operation"], answer:0, explanation:"FIFO = First In First Out, used in queues and page replacement."},
{id:104, topic:"os", difficulty:"hard", question:"In Banker's Algorithm, what does 'safe state' mean?", options:["No deadlock possible","System can allocate resources to all processes in some order","All processes are running","Memory is full"], answer:1, explanation:"Safe state = there exists at least one sequence in which all processes can finish without deadlock."},
{id:105, topic:"os", difficulty:"medium", question:"What is the purpose of page table?", options:["Store files","Map virtual addresses to physical addresses","Schedule processes","Manage I/O"], answer:1, explanation:"Page table maps virtual page numbers to physical frame numbers."},

// ===== SECTION: DATA STRUCTURES =====
{id:106, topic:"dsa", difficulty:"easy", question:"What is the time complexity of inserting at the beginning of a linked list?", options:["O(1)","O(n)","O(log n)","O(n²)"], answer:0, explanation:"Inserting at head of linked list is O(1) — just update the head pointer."},
{id:107, topic:"dsa", difficulty:"easy", question:"Which traversal of BST gives sorted output?", options:["Preorder","Postorder","Inorder","Level order"], answer:2, explanation:"Inorder traversal (Left-Root-Right) of BST gives elements in sorted order."},
{id:108, topic:"dsa", difficulty:"medium", question:"What is the worst case time complexity of Quick Sort?", options:["O(n log n)","O(n²)","O(n)","O(log n)"], answer:1, explanation:"Quick Sort worst case is O(n²) when pivot is always the smallest/largest element."},
{id:109, topic:"dsa", difficulty:"medium", question:"Minimum number of queues needed to implement a stack?", options:["1","2","3","4"], answer:1, explanation:"Two queues are needed to implement a stack."},
{id:110, topic:"dsa", difficulty:"medium", question:"Which data structure is used for implementing recursion?", options:["Queue","Stack","Array","Tree"], answer:1, explanation:"Stack (call stack) is used internally for recursion — stores function frames."},
{id:111, topic:"dsa", difficulty:"medium", question:"Height of a complete binary tree with n nodes is:", options:["O(n)","O(log n)","O(n²)","O(1)"], answer:1, explanation:"Complete binary tree height = floor(log₂ n) = O(log n)."},
{id:112, topic:"dsa", difficulty:"hard", question:"What is the time complexity of building a heap from an array?", options:["O(n log n)","O(n)","O(n²)","O(log n)"], answer:1, explanation:"Building a heap (heapify) from an array is O(n), not O(n log n)."},
{id:113, topic:"dsa", difficulty:"easy", question:"A binary tree node has at most ___ children.", options:["1","2","3","Any number"], answer:1, explanation:"Binary tree: each node has at most 2 children (left and right)."},
{id:114, topic:"dsa", difficulty:"medium", question:"Which algorithm is used to find shortest path in a weighted graph?", options:["BFS","DFS","Dijkstra's","Binary Search"], answer:2, explanation:"Dijkstra's algorithm finds shortest path in weighted graphs with non-negative edges."},
{id:115, topic:"dsa", difficulty:"medium", question:"What is the space complexity of Merge Sort?", options:["O(1)","O(log n)","O(n)","O(n²)"], answer:2, explanation:"Merge Sort needs O(n) extra space for the temporary array during merging."},
{id:116, topic:"dsa", difficulty:"easy", question:"What is a hash collision?", options:["Hash table is full","Two keys map to the same index","Hash function fails","Memory leak"], answer:1, explanation:"Collision occurs when two different keys hash to the same bucket/index."},
{id:117, topic:"dsa", difficulty:"medium", question:"Which is NOT a method to handle hash collisions?", options:["Chaining","Linear Probing","Binary Search","Double Hashing"], answer:2, explanation:"Binary Search is a searching algorithm, not a collision resolution technique."},
{id:118, topic:"dsa", difficulty:"medium", question:"Postfix expression: 5 3 + 8 * evaluates to:", options:["64","29","40","44"], answer:0, explanation:"5+3=8, 8*8=64"},
{id:119, topic:"dsa", difficulty:"easy", question:"Number of edges in a tree with n nodes:", options:["n","n-1","n+1","2n"], answer:1, explanation:"A tree with n nodes always has exactly n-1 edges."},
{id:120, topic:"dsa", difficulty:"hard", question:"Worst case time complexity of search in a balanced BST:", options:["O(n)","O(log n)","O(1)","O(n log n)"], answer:1, explanation:"Balanced BST maintains O(log n) height, so search is O(log n)."},

// ===== MORE QUANTITATIVE =====
{id:121, topic:"quantitative", difficulty:"easy", question:"What is 15% of 600?", options:["80","90","100","75"], answer:1, explanation:"15% of 600 = (15/100) × 600 = 90"},
{id:122, topic:"quantitative", difficulty:"medium", question:"A car travels at 60 km/h for 2 hrs and 40 km/h for 3 hrs. Average speed?", options:["48 km/h","50 km/h","52 km/h","45 km/h"], answer:0, explanation:"Total distance = 120 + 120 = 240. Total time = 5. Avg = 240/5 = 48 km/h"},
{id:123, topic:"quantitative", difficulty:"medium", question:"If a number is divisible by both 3 and 5, it is divisible by:", options:["8","10","15","20"], answer:2, explanation:"LCM of 3 and 5 is 15. So the number is divisible by 15."},
{id:124, topic:"quantitative", difficulty:"easy", question:"The square root of 144 is:", options:["10","11","12","13"], answer:2, explanation:"√144 = 12"},
{id:125, topic:"quantitative", difficulty:"medium", question:"In how many ways can 5 people be arranged in a row?", options:["60","100","120","150"], answer:2, explanation:"5! = 5×4×3×2×1 = 120"},

// ===== MORE LOGICAL =====
{id:126, topic:"logical", difficulty:"easy", question:"Complete: 1, 4, 9, 16, 25, ?", options:["30","36","42","49"], answer:1, explanation:"Perfect squares: 1², 2², 3², 4², 5², 6² = 36"},
{id:127, topic:"logical", difficulty:"medium", question:"If 'CAT' = 24, 'DOG' = 26, then 'COW' = ?", options:["38","41","43","45"], answer:1, explanation:"C=3, A=1, T=20 → 24. D=4, O=15, G=7 → 26. C=3, O=15, W=23 → 41."},
{id:128, topic:"logical", difficulty:"medium", question:"Which figure completes the pattern? Mirror image of L is:", options:["L","J","Γ","⌐"], answer:1, explanation:"Mirror image of L is J (reversed)."},
{id:129, topic:"logical", difficulty:"easy", question:"Pointing to a man, Sita said 'He is the son of my grandfather's only son.' How is the man related to Sita?", options:["Father","Brother","Uncle","Cousin"], answer:1, explanation:"Grandfather's only son = father. Son of father = brother."},
{id:130, topic:"logical", difficulty:"medium", question:"If South-East becomes North, then North-East becomes:", options:["South","West","North-West","South-West"], answer:1, explanation:"135° clockwise rotation: NE → W"},

// ===== MORE PROGRAMMING =====
{id:131, topic:"programming", difficulty:"easy", question:"What is the output of: print(type(5.0)) in Python?", options:["<class 'int'>","<class 'float'>","<class 'str'>","<class 'double'>"], answer:1, explanation:"5.0 is a floating point number → float type."},
{id:132, topic:"programming", difficulty:"medium", question:"What is method overloading?", options:["Redefining parent method in child","Same method name with different parameters in same class","Creating multiple classes","None"], answer:1, explanation:"Overloading = same method name, different parameter list in SAME class."},
{id:133, topic:"programming", difficulty:"medium", question:"What is the output of: print(2**3**2) in Python?", options:["64","512","36","81"], answer:1, explanation:"** is right-associative: 2**(3**2) = 2**9 = 512"},
{id:134, topic:"programming", difficulty:"easy", question:"Which keyword is used to inherit a class in Java?", options:["implements","extends","inherits","super"], answer:1, explanation:"'extends' keyword is used for class inheritance in Java."},
{id:135, topic:"programming", difficulty:"medium", question:"What is a constructor in OOP?", options:["A destructor","A special method called when object is created","A loop","A variable"], answer:1, explanation:"Constructor is automatically called when an object is instantiated, initializes the object."},
{id:136, topic:"programming", difficulty:"easy", question:"What is the index of the first element in an array (most languages)?", options:["1","0","-1","None"], answer:1, explanation:"Arrays are 0-indexed in most languages (C, Java, Python, etc.)"},
{id:137, topic:"programming", difficulty:"medium", question:"What is an abstract class?", options:["A class that cannot be instantiated and may contain abstract methods","A normal class","A static class","A final class"], answer:0, explanation:"Abstract class cannot be instantiated directly and can have abstract (unimplemented) methods."},
{id:138, topic:"programming", difficulty:"hard", question:"What is the output of:\nx = [1,2,3]\ny = x\ny.append(4)\nprint(x)", options:["[1,2,3]","[1,2,3,4]","[4,1,2,3]","Error"], answer:1, explanation:"y = x creates a reference (alias), not a copy. Both point to same list."},
{id:139, topic:"programming", difficulty:"medium", question:"What is garbage collection?", options:["Deleting files","Automatic memory reclamation of unreferenced objects","Disk cleanup","Cache clearing"], answer:1, explanation:"GC automatically frees memory occupied by objects no longer referenced."},
{id:140, topic:"programming", difficulty:"easy", question:"What is the difference between '=' and '==' in programming?", options:["No difference","= is assignment, == is comparison","= is comparison, == is assignment","Both are comparison"], answer:1, explanation:"= assigns a value, == compares two values for equality."},

// ===== MORE VERBAL =====
{id:141, topic:"verbal", difficulty:"easy", question:"Choose the synonym of 'Ephemeral':", options:["Permanent","Short-lived","Strong","Beautiful"], answer:1, explanation:"Ephemeral = lasting for a very short time."},
{id:142, topic:"verbal", difficulty:"medium", question:"Choose the correct article: '___ honest man is respected.'", options:["A","An","The","No article"], answer:1, explanation:"'An' is used before words starting with a vowel sound. 'Honest' starts with a vowel sound."},
{id:143, topic:"verbal", difficulty:"easy", question:"What is the plural of 'child'?", options:["Childs","Children","Childrens","Child's"], answer:1, explanation:"'Children' is the irregular plural of 'child'."},
{id:144, topic:"verbal", difficulty:"medium", question:"'Hit the nail on the head' means:", options:["Carpentry work","To be exactly right","To cause pain","To work hard"], answer:1, explanation:"It means to describe exactly what is causing a situation or problem."},
{id:145, topic:"verbal", difficulty:"medium", question:"Choose the correct form: 'If I ___ you, I would study harder.'", options:["am","was","were","be"], answer:2, explanation:"Subjunctive mood uses 'were' for hypothetical situations: 'If I were you...'"},

// ===== MORE DBMS =====
{id:146, topic:"dbms", difficulty:"medium", question:"What is a VIEW in SQL?", options:["A physical table","A virtual table based on a SELECT query","An index","A stored procedure"], answer:1, explanation:"View is a virtual table based on the result of a SELECT query. Does not store data physically."},
{id:147, topic:"dbms", difficulty:"medium", question:"What is the difference between HAVING and WHERE?", options:["No difference","WHERE filters rows before grouping, HAVING filters after grouping","HAVING is faster","WHERE works with groups"], answer:1, explanation:"WHERE filters individual rows. HAVING filters groups (used with GROUP BY)."},
{id:148, topic:"dbms", difficulty:"hard", question:"What does BCNF ensure beyond 3NF?", options:["No redundancy at all","For every FD X→Y, X must be a superkey","Atomic values","No partial dependency"], answer:1, explanation:"BCNF: Every determinant must be a superkey. Stricter than 3NF."},
{id:149, topic:"dbms", difficulty:"easy", question:"Which SQL clause is used to sort results?", options:["GROUP BY","SORT BY","ORDER BY","ARRANGE BY"], answer:2, explanation:"ORDER BY clause sorts the result set in ascending (ASC) or descending (DESC) order."},
{id:150, topic:"dbms", difficulty:"medium", question:"What is a stored procedure?", options:["A saved SQL query","A precompiled collection of SQL statements stored in the database","A view","A trigger"], answer:1, explanation:"Stored procedure = precompiled SQL code that can be reused. Improves performance and security."},

// ===== MORE MIXED =====
{id:151, topic:"programming", difficulty:"medium", question:"What is the difference between ArrayList and LinkedList in Java?", options:["No difference","ArrayList uses array (fast access), LinkedList uses nodes (fast insert/delete)","LinkedList is faster for everything","ArrayList cannot grow"], answer:1, explanation:"ArrayList: O(1) random access, O(n) insert/delete. LinkedList: O(n) access, O(1) insert/delete at known position."},
{id:152, topic:"quantitative", difficulty:"easy", question:"What is the value of 7! (factorial)?", options:["720","5040","40320","362880"], answer:1, explanation:"7! = 7×6×5×4×3×2×1 = 5040"},
{id:153, topic:"logical", difficulty:"easy", question:"Which number is the odd one out: 2, 3, 5, 7, 11, 13, 15?", options:["2","11","13","15"], answer:3, explanation:"15 is not a prime number (15 = 3×5). All others are primes."},
{id:154, topic:"quantitative", difficulty:"medium", question:"The area of a circle with radius 7 cm is (π = 22/7):", options:["144 cm²","154 cm²","164 cm²","174 cm²"], answer:1, explanation:"Area = πr² = (22/7) × 49 = 154 cm²"},
{id:155, topic:"networking", difficulty:"medium", question:"What is REST API?", options:["A database","An architectural style for web services using HTTP methods","A programming language","An operating system"], answer:1, explanation:"REST = Representational State Transfer. Uses HTTP methods (GET, POST, PUT, DELETE) for CRUD operations."},
{id:156, topic:"os", difficulty:"easy", question:"What is a kernel?", options:["A type of shell","Core component of OS managing system resources","A programming language","A database"], answer:1, explanation:"Kernel is the core of OS — manages memory, processes, I/O, and hardware communication."},
{id:157, topic:"dsa", difficulty:"medium", question:"Which algorithm uses 'divide and conquer' approach?", options:["Bubble Sort","Merge Sort","Insertion Sort","Selection Sort"], answer:1, explanation:"Merge Sort divides array into halves, sorts each half, then merges."},
{id:158, topic:"programming", difficulty:"medium", question:"What is the output of: print('Hello'[1:4]) in Python?", options:["Hel","ell","llo","Hell"], answer:1, explanation:"String slicing [1:4] gives characters at index 1,2,3 = 'ell'"},
{id:159, topic:"quantitative", difficulty:"hard", question:"A man rows upstream 10 km in 5 hrs and downstream 10 km in 2 hrs. Speed of stream?", options:["0.5 km/h","1 km/h","1.5 km/h","2 km/h"], answer:2, explanation:"Upstream = 2 km/h, Downstream = 5 km/h. Stream = (5-2)/2 = 1.5 km/h"},
{id:160, topic:"dbms", difficulty:"medium", question:"What is a trigger in SQL?", options:["A query","A stored program that executes automatically on table events","A view","An index"], answer:1, explanation:"Trigger = automatically executed procedure when an INSERT, UPDATE, or DELETE occurs on a table."},

// ===== ADDITIONAL QUESTIONS FOR COMPREHENSIVE COVERAGE =====
{id:161, topic:"quantitative", difficulty:"medium", question:"If the price of a commodity increases by 25%, by what % should consumption decrease to keep expenditure same?", options:["20%","25%","30%","15%"], answer:0, explanation:"Decrease = (25/125)×100 = 20%. Formula: r/(100+r) × 100"},
{id:162, topic:"quantitative", difficulty:"medium", question:"The difference between CI and SI on ₹5000 for 2 years at 4% per annum is:", options:["₹2","₹4","₹8","₹10"], answer:2, explanation:"Difference = P(r/100)² = 5000 × (4/100)² = 5000 × 0.0016 = ₹8"},
{id:163, topic:"logical", difficulty:"medium", question:"If + means ×, − means ÷, × means −, ÷ means +, then 8 + 6 − 2 × 5 ÷ 3 = ?", options:["22","27","24","21"], answer:1, explanation:"Replace: 8 × 6 ÷ 2 − 5 + 3 = 48/2 - 5 + 3 = 24 - 5 + 3 = 22. Hmm, let me recalculate with BODMAS: 8×6 = 48, 48÷2 = 24, 24−5 = 19, 19+3 = 22"},
{id:164, topic:"verbal", difficulty:"medium", question:"Choose the correct sentence:", options:["He is more wiser than her","He is wiser than her","He is most wiser than her","He is wise than her"], answer:1, explanation:"'Wiser' is already comparative. Don't add 'more' with comparative form."},
{id:165, topic:"programming", difficulty:"hard", question:"What is the time complexity of finding an element in an unsorted array?", options:["O(1)","O(log n)","O(n)","O(n²)"], answer:2, explanation:"Linear search through unsorted array is O(n) — must check each element."},
{id:166, topic:"dsa", difficulty:"medium", question:"A max-heap with values [90, 80, 70, 60, 50]. After removing max, the heap is:", options:["[80, 60, 70, 50]","[80, 70, 60, 50]","[70, 60, 50, 80]","[80, 50, 70, 60]"], answer:0, explanation:"Remove 90, replace with last (50), heapify down: 50 swaps with 80, then with 60 → [80, 60, 70, 50]"},
{id:167, topic:"networking", difficulty:"easy", question:"What is the full form of HTTP?", options:["HyperText Transfer Protocol","HyperText Transmission Protocol","High Transfer Text Protocol","HyperText Transit Protocol"], answer:0, explanation:"HTTP = HyperText Transfer Protocol"},
{id:168, topic:"os", difficulty:"medium", question:"Which page replacement algorithm is considered optimal?", options:["FIFO","LRU","Optimal (Belady's)","Clock"], answer:2, explanation:"Optimal (Belady's) algorithm replaces the page that won't be used for the longest time. Theoretical ideal."},
{id:169, topic:"quantitative", difficulty:"easy", question:"Sum of first 10 natural numbers:", options:["45","55","65","50"], answer:1, explanation:"n(n+1)/2 = 10×11/2 = 55"},
{id:170, topic:"logical", difficulty:"easy", question:"Complete: J, F, M, A, M, J, J, A, S, O, N, ?", options:["D","L","M","P"], answer:0, explanation:"First letters of months: January to December → D"},

// ===== EVEN MORE QUESTIONS FOR DIVERSITY =====
{id:171, topic:"quantitative", difficulty:"medium", question:"A shopkeeper mixes 30 kg of rice at ₹30/kg with 20 kg at ₹36/kg. What is the average price per kg?", options:["₹32.40","₹33.00","₹31.20","₹34.00"], answer:0, explanation:"Total cost = 900 + 720 = 1620. Total weight = 50. Avg = 1620/50 = ₹32.40"},
{id:172, topic:"programming", difficulty:"easy", question:"What does 'continue' statement do in a loop?", options:["Exits the loop","Skips the rest of current iteration and continues to next","Pauses the loop","Restarts from beginning"], answer:1, explanation:"'continue' skips remaining code in current iteration and moves to next iteration."},
{id:173, topic:"dbms", difficulty:"easy", question:"Which SQL command is used to add a new row?", options:["ADD","CREATE","INSERT","APPEND"], answer:2, explanation:"INSERT INTO table_name VALUES (...) adds a new row."},
{id:174, topic:"networking", difficulty:"medium", question:"What is a subnet mask used for?", options:["Hiding IP address","Dividing IP address into network and host portions","Encrypting data","Speed control"], answer:1, explanation:"Subnet mask separates the network portion from the host portion of an IP address."},
{id:175, topic:"os", difficulty:"easy", question:"What is multithreading?", options:["Multiple CPUs","Multiple threads executing concurrently within a process","Multiple processes","Multiple users"], answer:1, explanation:"Multithreading = concurrent execution of two or more threads within a single process."},
{id:176, topic:"dsa", difficulty:"easy", question:"What is a queue?", options:["LIFO structure","FIFO structure","Random access structure","Tree structure"], answer:1, explanation:"Queue follows First In First Out (FIFO) principle."},
{id:177, topic:"verbal", difficulty:"easy", question:"Antonym of 'Diligent':", options:["Lazy","Active","Careful","Smart"], answer:0, explanation:"Diligent means hardworking. Lazy is the opposite."},
{id:178, topic:"logical", difficulty:"medium", question:"If in a certain code, DOME = 4567 and MEAL = 5789, what is MODE?", options:["5647","5746","5647","5674"], answer:0, explanation:"M=5, O=6, D=4, E=7, A=8, L=9. MODE = 5647"},
{id:179, topic:"programming", difficulty:"medium", question:"What is the output of: bool(0), bool(''), bool(None), bool([]) in Python?", options:["All True","All False","Mixed results","Error"], answer:1, explanation:"0, empty string, None, empty list are all falsy in Python → all return False."},
{id:180, topic:"quantitative", difficulty:"hard", question:"If log₂(x) = 5, then x = ?", options:["10","25","32","64"], answer:2, explanation:"log₂(x) = 5 → x = 2⁵ = 32"},

// ===== ADDITIONAL QUESTIONS TO REACH 200+ =====
{id:181, topic:"programming", difficulty:"medium", question:"What is the difference between stack and heap memory?", options:["No difference","Stack is for local variables (LIFO), heap is for dynamic allocation","Heap is faster","Stack is unlimited"], answer:1, explanation:"Stack: fixed size, LIFO, local variables. Heap: dynamic allocation, objects, managed by GC."},
{id:182, topic:"quantitative", difficulty:"easy", question:"What is the GCD/HCF of 24 and 36?", options:["6","8","12","18"], answer:2, explanation:"Factors of 24: 1,2,3,4,6,8,12,24. Factors of 36: 1,2,3,4,6,9,12,18,36. GCD = 12"},
{id:183, topic:"dbms", difficulty:"medium", question:"What is the difference between clustered and non-clustered index?", options:["No difference","Clustered sorts physical data (1 per table), non-clustered is separate structure (multiple allowed)","Non-clustered is faster","Clustered uses more space"], answer:1, explanation:"Clustered index determines physical order of data. Only one per table. Non-clustered is a separate structure pointing to data."},
{id:184, topic:"networking", difficulty:"hard", question:"What are the steps in a TCP 3-way handshake?", options:["SYN → ACK → FIN","SYN → SYN-ACK → ACK","ACK → SYN → FIN","SYN → FIN → ACK"], answer:1, explanation:"1. Client sends SYN. 2. Server responds SYN+ACK. 3. Client sends ACK. Connection established."},
{id:185, topic:"os", difficulty:"medium", question:"What is the producer-consumer problem?", options:["A design pattern","Synchronization problem with bounded buffer between producer and consumer","A sorting problem","A networking issue"], answer:1, explanation:"Producer generates data into bounded buffer, consumer removes it. Needs synchronization to prevent overflow/underflow."},
{id:186, topic:"logical", difficulty:"easy", question:"How many triangles in a figure formed by connecting all vertices of a pentagon?", options:["5","8","10","15"], answer:2, explanation:"C(5,3) = 10 triangles can be formed from 5 points."},
{id:187, topic:"verbal", difficulty:"medium", question:"'To cry over spilt milk' means:", options:["To clean up","To regret over something that cannot be undone","To be happy","To work hard"], answer:1, explanation:"It means to waste time worrying about things that have already happened and cannot be changed."},
{id:188, topic:"programming", difficulty:"easy", question:"What is the output of: len('Hello World') in Python?", options:["10","11","12","Error"], answer:1, explanation:"'Hello World' has 11 characters including the space."},
{id:189, topic:"quantitative", difficulty:"medium", question:"A train 200m long crosses a pole in 10 seconds. Its speed is:", options:["20 m/s","72 km/h","Both A and B","36 km/h"], answer:2, explanation:"Speed = 200/10 = 20 m/s = 20 × 3.6 = 72 km/h. Both A and B are correct."},
{id:190, topic:"dsa", difficulty:"medium", question:"What is the amortized time complexity of operations in a dynamic array (ArrayList)?", options:["O(n)","O(1)","O(log n)","O(n²)"], answer:1, explanation:"Amortized O(1) for append. Occasional O(n) resizing is spread across all operations."},

{id:191, topic:"programming", difficulty:"medium", question:"What is the difference between 'public', 'private', and 'protected' in Java?", options:["No difference","public: everywhere, private: same class, protected: same package + subclasses","All are same access level","private is most accessible"], answer:1, explanation:"public > protected > default > private in terms of accessibility."},
{id:192, topic:"quantitative", difficulty:"easy", question:"Convert 0.75 to a fraction:", options:["3/4","7/5","1/4","2/3"], answer:0, explanation:"0.75 = 75/100 = 3/4"},
{id:193, topic:"logical", difficulty:"medium", question:"A clock shows 3:15. What is the angle between hour and minute hands?", options:["0°","7.5°","22.5°","15°"], answer:1, explanation:"At 3:15, minute hand at 90°, hour hand at 90° + 7.5° = 97.5°. Angle = 7.5°"},
{id:194, topic:"verbal", difficulty:"easy", question:"Choose the synonym of 'Meticulous':", options:["Careless","Thorough","Quick","Lazy"], answer:1, explanation:"Meticulous means showing great attention to detail; thorough."},
{id:195, topic:"networking", difficulty:"easy", question:"What is the maximum value of a single octet in an IPv4 address?", options:["128","255","256","512"], answer:1, explanation:"Each octet is 8 bits → max value = 2⁸ - 1 = 255"},
{id:196, topic:"os", difficulty:"easy", question:"What is a context switch?", options:["Switching between applications","Saving/restoring state of a process so another can run","Switching networks","Changing OS"], answer:1, explanation:"Context switch saves the state (registers, PC) of current process and loads the state of the next process."},
{id:197, topic:"dbms", difficulty:"easy", question:"What does GROUP BY do in SQL?", options:["Groups rows with same values in specified columns","Sorts data","Deletes groups","Creates groups of tables"], answer:0, explanation:"GROUP BY groups rows that have same values and is often used with aggregate functions (COUNT, SUM, AVG)."},
{id:198, topic:"dsa", difficulty:"easy", question:"What is a linked list?", options:["Array of elements","Linear data structure where elements are stored in nodes connected by pointers","A type of tree","A hash table"], answer:1, explanation:"Linked list: nodes containing data and a pointer to the next node. Non-contiguous memory."},
{id:199, topic:"programming", difficulty:"hard", question:"What is the output of:\nfor i in range(5):\n  if i == 3:\n    break\n  print(i, end=' ')", options:["0 1 2 3","0 1 2","0 1 2 3 4","1 2 3"], answer:1, explanation:"Loop prints 0, 1, 2, then when i=3, break exits the loop."},
{id:200, topic:"quantitative", difficulty:"medium", question:"If 6 men can do a work in 12 days, how many men are needed to do it in 4 days?", options:["12","18","24","36"], answer:1, explanation:"Men × Days = constant. 6 × 12 = M × 4. M = 72/4 = 18"}
];

// Topic metadata for display
const TOPIC_META = {
    quantitative: { name: "Quantitative Aptitude", icon: "🔢", color: "#667eea" },
    logical: { name: "Logical Reasoning", icon: "🧩", color: "#f5576c" },
    verbal: { name: "Verbal Ability", icon: "📝", color: "#43e97b" },
    programming: { name: "Programming Concepts", icon: "💻", color: "#4facfe" },
    dbms: { name: "DBMS & SQL", icon: "🗃️", color: "#fa709a" },
    networking: { name: "Computer Networks", icon: "🌐", color: "#fbc2eb" },
    os: { name: "Operating Systems", icon: "⚙️", color: "#a18cd1" },
    dsa: { name: "Data Structures", icon: "🧮", color: "#f093fb" }
};

// Flashcards Data
const FLASHCARD_DATA = [
    // Quantitative Formulas
    {topic:"quantitative", front:"Speed Formula", back:"Speed = Distance / Time\nTime = Distance / Speed\nDistance = Speed × Time\n\nConversion: km/h to m/s → multiply by 5/18"},
    {topic:"quantitative", front:"Profit & Loss", back:"Profit = SP - CP\nProfit% = (Profit/CP) × 100\nSP = CP × (100 + P%)/100\nDiscount% = (Discount/MP) × 100\nSP = MP × (100 - D%)/100"},
    {topic:"quantitative", front:"Simple Interest", back:"SI = (P × R × T) / 100\nAmount = P + SI\nP = Principal, R = Rate%, T = Time in years"},
    {topic:"quantitative", front:"Compound Interest", back:"A = P(1 + R/100)^T\nCI = A - P\nCI - SI (2 years) = P(R/100)²"},
    {topic:"quantitative", front:"Percentage Shortcuts", back:"x% increase then x% decrease = net (x²/100)% decrease\nSuccessive discounts: a% then b% = (a+b-ab/100)%\nTo find what % A is of B: (A/B) × 100"},
    {topic:"quantitative", front:"Work & Time", back:"If A does work in 'a' days: Rate = 1/a per day\nA+B together: 1/a + 1/b = (a+b)/ab\nTime together = ab/(a+b) days"},
    {topic:"quantitative", front:"Ratio & Proportion", back:"A:B = a:b means A/B = a/b\nDuplicate ratio of a:b = a²:b²\nCompound ratio of a:b and c:d = ac:bd"},
    {topic:"quantitative", front:"Average", back:"Average = Sum / Count\nWeighted Avg = Σ(wᵢxᵢ) / Σwᵢ\nIf avg of n numbers is A, sum = n×A"},
    {topic:"quantitative", front:"Permutation & Combination", back:"nPr = n!/(n-r)! — arrangement, order matters\nnCr = n!/[r!(n-r)!] — selection, order doesn't matter\nn! = n × (n-1) × ... × 1"},
    {topic:"quantitative", front:"Pipes & Cisterns", back:"If pipe fills in 'a' hrs: rate = 1/a\nIf pipe empties in 'b' hrs: rate = -1/b\nNet rate (fill+empty) = 1/a - 1/b\nTime = 1/net_rate"},

    // Programming Concepts
    {topic:"programming", front:"Four Pillars of OOP", back:"1. Encapsulation — Bundling data + methods, hiding internals\n2. Abstraction — Hiding complexity, showing interface only\n3. Inheritance — Child inherits from parent (code reuse)\n4. Polymorphism — Same interface, different behavior"},
    {topic:"programming", front:"Time Complexities", back:"O(1) — Hash lookup, array access\nO(log n) — Binary search\nO(n) — Linear search, single loop\nO(n log n) — Merge sort, Quick sort (avg)\nO(n²) — Bubble sort, nested loops\nO(2^n) — Recursive Fibonacci"},
    {topic:"programming", front:"Stack vs Queue", back:"Stack: LIFO (Last In First Out)\n- push, pop, peek\n- Uses: undo, function calls, DFS\n\nQueue: FIFO (First In First Out)\n- enqueue, dequeue, front\n- Uses: BFS, scheduling, printer"},
    {topic:"programming", front:"String vs StringBuilder (Java)", back:"String: Immutable, thread-safe, new object on change\nStringBuilder: Mutable, NOT thread-safe, fast\nStringBuffer: Mutable, thread-safe, slower\n\nUse StringBuilder for string building in loops"},
    {topic:"programming", front:"Array vs Linked List", back:"Array: Contiguous memory, O(1) access, O(n) insert\nLinked List: Non-contiguous, O(n) access, O(1) insert\n\nArray → frequent reads\nLinked List → frequent inserts/deletes"},

    // DBMS
    {topic:"dbms", front:"SQL Commands Classification", back:"DDL (Define): CREATE, ALTER, DROP, TRUNCATE\nDML (Manipulate): SELECT, INSERT, UPDATE, DELETE\nDCL (Control): GRANT, REVOKE\nTCL (Transaction): COMMIT, ROLLBACK, SAVEPOINT"},
    {topic:"dbms", front:"Normalization Forms", back:"1NF: Atomic values, no repeating groups\n2NF: 1NF + no partial dependency\n3NF: 2NF + no transitive dependency\nBCNF: Every determinant is a superkey"},
    {topic:"dbms", front:"SQL Joins", back:"INNER JOIN: matching rows only\nLEFT JOIN: all left + matching right\nRIGHT JOIN: all right + matching left\nFULL OUTER: all rows from both\nCROSS JOIN: cartesian product"},
    {topic:"dbms", front:"ACID Properties", back:"Atomicity: All or nothing\nConsistency: Valid state to valid state\nIsolation: Transactions don't interfere\nDurability: Committed data survives crashes"},

    // Operating Systems
    {topic:"os", front:"Process vs Thread", back:"Process: Independent, own memory, heavy switch, IPC needed\nThread: Within process, shared memory, light switch\n\nProcess → isolation\nThread → parallelism within app"},
    {topic:"os", front:"Deadlock Conditions (Coffman)", back:"ALL 4 must hold for deadlock:\n1. Mutual Exclusion\n2. Hold and Wait\n3. No Preemption\n4. Circular Wait\n\nPrevent by breaking ANY one condition"},
    {topic:"os", front:"Page Replacement Algorithms", back:"FIFO: Replace oldest page\nLRU: Replace least recently used\nOptimal: Replace page not needed for longest\nClock: Circular FIFO with reference bit"},
    {topic:"os", front:"CPU Scheduling Algorithms", back:"FCFS: First Come First Served (non-preemptive)\nSJF: Shortest Job First (optimal avg wait)\nRound Robin: Time quantum based (preemptive)\nPriority: Based on priority values"},

    // Computer Networks
    {topic:"networks", front:"OSI Model Layers", back:"7. Application (HTTP, FTP, DNS)\n6. Presentation (SSL, JPEG)\n5. Session (NetBIOS)\n4. Transport (TCP, UDP)\n3. Network (IP, ICMP)\n2. Data Link (Ethernet, ARP)\n1. Physical (Cables, Signals)"},
    {topic:"networks", front:"TCP vs UDP", back:"TCP: Reliable, connection-oriented, ordered, slower\n- Uses: HTTP, FTP, Email, SSH\n\nUDP: Unreliable, connectionless, unordered, faster\n- Uses: DNS, Streaming, Gaming, VoIP"},
    {topic:"networks", front:"HTTP Status Codes", back:"200: OK\n201: Created\n301: Moved Permanently\n400: Bad Request\n401: Unauthorized\n403: Forbidden\n404: Not Found\n500: Internal Server Error"},
    {topic:"networks", front:"REST API Methods", back:"GET: Read/retrieve (idempotent)\nPOST: Create new resource\nPUT: Update/replace (idempotent)\nPATCH: Partial update\nDELETE: Remove (idempotent)"},

    // TCS Facts
    {topic:"tcs", front:"TCS — Basic Facts", back:"Founded: 1968 by J.R.D. Tata\nHQ: Mumbai, Maharashtra\nCEO: K. Krithivasan (since 2023)\nTagline: 'Building on Belief'\nEmployees: ~593,000+"},
    {topic:"tcs", front:"TCS — Business Facts", back:"Revenue: US$31 billion (FY 2025)\nParent: Tata Group (71.74%)\nPresence: 150+ locations, 46 countries\nDigital Package: 7-9 LPA for freshers\nILP: Initial Learning Program (training for freshers)"},
    {topic:"tcs", front:"TCS — Key Products", back:"BaNCS: Banking software\nIgnio: AI/ML platform for operations\nMasterCraft: DevOps automation\nQuartz: Blockchain solutions\nHOBS: Telecom billing\nOmniStore: Retail solutions"},
    {topic:"tcs", front:"TCS Ion", back:"Digital platform for:\n- Learning & Assessment\n- Online exams (NQT)\n- Certification programs\n- HR solutions\n- Government recruitment drives"}
];
